package inertia

import "html/template"

// RenderOption configures a single Render call.
type RenderOption func(*renderOptions)

type renderOptions struct {
	data             map[string]any
	inertiaHead      template.HTML
	viteTags         template.HTML
	preserveFragment bool
}

// WithViewData adds extra data for the RootView template.
func WithViewData(data map[string]any) RenderOption {
	return func(opts *renderOptions) {
		opts.data = data
	}
}

// WithInertiaHead sets HTML that should be rendered in the Inertia head placeholder.
func WithInertiaHead(head template.HTML) RenderOption {
	return func(opts *renderOptions) {
		opts.inertiaHead = head
	}
}

// WithViteTags sets HTML tags generated by Vite.
func WithViteTags(tags template.HTML) RenderOption {
	return func(opts *renderOptions) {
		opts.viteTags = tags
	}
}

// WithRenderPreserveFragment sets Page.PreserveFragment for the rendered page.
func WithRenderPreserveFragment() RenderOption {
	return func(opts *renderOptions) {
		opts.preserveFragment = true
	}
}
