package inertia

import "html/template"

// RenderOption configures a single Render call.
type RenderOption func(*renderOptions)

type renderOptions struct {
	data             map[string]any
	inertiaHead      template.HTML
	viteTags         template.HTML
	preserveFragment bool
	encryptHistory   bool
	clearHistory     bool
}

// WithViewData adds extra data for the RootView template.
func WithViewData(data map[string]any) RenderOption {
	return func(opts *renderOptions) {
		opts.data = data
	}
}

// WithInertiaHead sets HTML that should be rendered in the Inertia head placeholder.
func WithInertiaHead(head template.HTML) RenderOption {
	return func(opts *renderOptions) {
		opts.inertiaHead = head
	}
}

// WithViteTags sets HTML tags generated by Vite.
func WithViteTags(tags template.HTML) RenderOption {
	return func(opts *renderOptions) {
		opts.viteTags = tags
	}
}

// WithRenderPreserveFragment sets Page.PreserveFragment for the rendered page.
func WithRenderPreserveFragment() RenderOption {
	return func(opts *renderOptions) {
		opts.preserveFragment = true
	}
}

// WithEncryptHistory sets Page.EncryptHistory for the rendered page.
func WithEncryptHistory(encrypt ...bool) RenderOption {
	return func(opts *renderOptions) {
		opts.encryptHistory = true
		if len(encrypt) > 0 {
			opts.encryptHistory = encrypt[0]
		}
	}
}

// WithClearHistory sets Page.ClearHistory for the rendered page.
func WithClearHistory(clear ...bool) RenderOption {
	return func(opts *renderOptions) {
		opts.clearHistory = true
		if len(clear) > 0 {
			opts.clearHistory = clear[0]
		}
	}
}
